#
# Automagically generated by Approximatrix Simply Fortran 2.9
#
FC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\ar.exe"
TOUCH="C:\Program Files (x86)\Simply Fortran 2\fwin\wtouch.exe"
WRC="C:\PROGRA~2\SIMPLY~1\MINGW-~1\bin\windres.exe"
RM=rm -f

IDIR=-IC:/Users/pmayer/AppData/Local///sfpm/32/include 
# -I error: Directory C:\Program Files (x86)\Simply Fortran 2\mingw-w64\include\ does not exist

LDIR=-LC:/PROGRA~2/SIMPLY~1/MINGW-~1/lib/ -LC:/Users/pmayer/AppData/Local///sfpm/32/lib 


SPECIALFLAGS=-g -m32 $(IDIR)

RCFLAGS=-O coff -F pe-i386

PRJ_FFLAGS=
PRJ_CFLAGS=
PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS)  $(PRJ_FFLAGS) -Jmodules 

CFLAGS=-g -m32  $(IDIR) $(PRJ_CFLAGS)

"build\geometry.o": ".\geometry.f90" "modules\pmatypy.mod"
	@echo Compiling .\geometry.f90
	@$(FC) -c -o "build\geometry.o" $(FFLAGS) ".\geometry.f90"
"modules\geometry.mod" : "build\geometry.o" .EXISTSONLY
	@echo Compiling .\geometry.f90
	@$(FC) -c -o "build\geometry.o" $(FFLAGS) ".\geometry.f90"

"build\global.o": ".\global.f90" "modules\geometry.mod" "modules\pmatypy.mod" "modules\pmatools.mod"
	@echo Compiling .\global.f90
	@$(FC) -c -o "build\global.o" $(FFLAGS) ".\global.f90"
"modules\global.mod" : "build\global.o" .EXISTSONLY
	@echo Compiling .\global.f90
	@$(FC) -c -o "build\global.o" $(FFLAGS) ".\global.f90"

"build\kreslitko.o": ".\kreslitko.f90" "modules\zobraz.mod" "modules\geometry.mod" "modules\pmatypy.mod" "modules\global.mod" "modules\pmatools.mod"
	@echo Compiling .\kreslitko.f90
	@$(FC) -c -o "build\kreslitko.o" $(FFLAGS) ".\kreslitko.f90"
"modules\kreslitko.mod" : "build\kreslitko.o" .EXISTSONLY
	@echo Compiling .\kreslitko.f90
	@$(FC) -c -o "build\kreslitko.o" $(FFLAGS) ".\kreslitko.f90"

"build\local.o": ".\local.f90" "modules\pmatypy.mod" "modules\geometry.mod" "modules\global.mod"
	@echo Compiling .\local.f90
	@$(FC) -c -o "build\local.o" $(FFLAGS) ".\local.f90"
"modules\local.mod" : "build\local.o" .EXISTSONLY
	@echo Compiling .\local.f90
	@$(FC) -c -o "build\local.o" $(FFLAGS) ".\local.f90"

"build\main.o": ".\main.f90" "modules\pmatypy.mod" "modules\local.mod" "modules\geometry.mod" "modules\solvers_jakub.mod" "modules\kreslitko.mod" "modules\mtx_jakub.mod" "modules\pmatools.mod" "modules\global.mod" "modules\mtx.mod" "modules\sparsematrix.mod"
	@echo Compiling .\main.f90
	@$(FC) -c -o "build\main.o" $(FFLAGS) ".\main.f90"

"build\mtx_jakub.o": ".\mtx_jakub.f90" "modules\pmatypy.mod"
	@echo Compiling .\mtx_jakub.f90
	@$(FC) -c -o "build\mtx_jakub.o" $(FFLAGS) ".\mtx_jakub.f90"
"modules\mtx_jakub.mod" : "build\mtx_jakub.o" .EXISTSONLY
	@echo Compiling .\mtx_jakub.f90
	@$(FC) -c -o "build\mtx_jakub.o" $(FFLAGS) ".\mtx_jakub.f90"

"build\solvers_jakub.o": ".\solvers_jakub.f90" "modules\pmatypy.mod" "modules\geometry.mod" "modules\global.mod" "modules\local.mod"
	@echo Compiling .\solvers_jakub.f90
	@$(FC) -c -o "build\solvers_jakub.o" $(FFLAGS) ".\solvers_jakub.f90"
"modules\solvers_jakub.mod" : "build\solvers_jakub.o" .EXISTSONLY
	@echo Compiling .\solvers_jakub.f90
	@$(FC) -c -o "build\solvers_jakub.o" $(FFLAGS) ".\solvers_jakub.f90"

"build\datasetup.o": "..\spec\datasetup.f90" "modules\pmatypy.mod" "modules\mtx.mod"
	@echo Compiling ..\spec\datasetup.f90
	@$(FC) -c -o "build\datasetup.o" $(FFLAGS) "..\spec\datasetup.f90"
"modules\datasetup.mod" : "build\datasetup.o" .EXISTSONLY
	@echo Compiling ..\spec\datasetup.f90
	@$(FC) -c -o "build\datasetup.o" $(FFLAGS) "..\spec\datasetup.f90"

"build\fullmatrix.o": "..\spec\fullmatrix.f90" "modules\pmatypy.mod" "modules\mtx.mod"
	@echo Compiling ..\spec\fullmatrix.f90
	@$(FC) -c -o "build\fullmatrix.o" $(FFLAGS) "..\spec\fullmatrix.f90"
"modules\fullmatrix.mod" : "build\fullmatrix.o" .EXISTSONLY
	@echo Compiling ..\spec\fullmatrix.f90
	@$(FC) -c -o "build\fullmatrix.o" $(FFLAGS) "..\spec\fullmatrix.f90"

"build\mtx.o": "..\spec\mtx.f90" "modules\pmatypy.mod"
	@echo Compiling ..\spec\mtx.f90
	@$(FC) -c -o "build\mtx.o" $(FFLAGS) "..\spec\mtx.f90"
"modules\mtx.mod" : "build\mtx.o" .EXISTSONLY
	@echo Compiling ..\spec\mtx.f90
	@$(FC) -c -o "build\mtx.o" $(FFLAGS) "..\spec\mtx.f90"

"build\mtxiotools.o": "..\spec\mtxiotools.f90" "modules\pmatypy.mod" "modules\mtx.mod" "modules\pmatools.mod"
	@echo Compiling ..\spec\mtxiotools.f90
	@$(FC) -c -o "build\mtxiotools.o" $(FFLAGS) "..\spec\mtxiotools.f90"
"modules\mtxiotools.mod" : "build\mtxiotools.o" .EXISTSONLY
	@echo Compiling ..\spec\mtxiotools.f90
	@$(FC) -c -o "build\mtxiotools.o" $(FFLAGS) "..\spec\mtxiotools.f90"

"build\mtxtester.o": "..\spec\mtxtester.f90" "modules\pmatypy.mod" "modules\mtx.mod" "modules\datasetup.mod" "modules\solvers.mod"
	@echo Compiling ..\spec\mtxtester.f90
	@$(FC) -c -o "build\mtxtester.o" $(FFLAGS) "..\spec\mtxtester.f90"
"modules\mtxtester_module.mod" : "build\mtxtester.o" .EXISTSONLY
	@echo Compiling ..\spec\mtxtester.f90
	@$(FC) -c -o "build\mtxtester.o" $(FFLAGS) "..\spec\mtxtester.f90"

"build\pmatools.o": "..\spec\pmatools.f90"
	@echo Compiling ..\spec\pmatools.f90
	@$(FC) -c -o "build\pmatools.o" $(FFLAGS) "..\spec\pmatools.f90"
"modules\pmatools.mod" : "build\pmatools.o" .EXISTSONLY
	@echo Compiling ..\spec\pmatools.f90
	@$(FC) -c -o "build\pmatools.o" $(FFLAGS) "..\spec\pmatools.f90"

"build\pmatypy.o": "..\spec\pmatypy.f90"
	@echo Compiling ..\spec\pmatypy.f90
	@$(FC) -c -o "build\pmatypy.o" $(FFLAGS) "..\spec\pmatypy.f90"
"modules\pmatypy.mod" : "build\pmatypy.o" .EXISTSONLY
	@echo Compiling ..\spec\pmatypy.f90
	@$(FC) -c -o "build\pmatypy.o" $(FFLAGS) "..\spec\pmatypy.f90"

"build\solvers.o": "..\spec\solvers.f90" "modules\pmatypy.mod" "modules\mtx.mod"
	@echo Compiling ..\spec\solvers.f90
	@$(FC) -c -o "build\solvers.o" $(FFLAGS) "..\spec\solvers.f90"
"modules\solvers.mod" : "build\solvers.o" .EXISTSONLY
	@echo Compiling ..\spec\solvers.f90
	@$(FC) -c -o "build\solvers.o" $(FFLAGS) "..\spec\solvers.f90"

"build\sparsematrix.o": "..\spec\sparsematrix.f90" "modules\pmatypy.mod" "modules\mtx.mod"
	@echo Compiling ..\spec\sparsematrix.f90
	@$(FC) -c -o "build\sparsematrix.o" $(FFLAGS) "..\spec\sparsematrix.f90"
"modules\sparsematrix.mod" : "build\sparsematrix.o" .EXISTSONLY
	@echo Compiling ..\spec\sparsematrix.f90
	@$(FC) -c -o "build\sparsematrix.o" $(FFLAGS) "..\spec\sparsematrix.f90"

"build\zobraz.o": "..\spec\zobraz.f90" "modules\pmatypy.mod" "modules\pmatools.mod"
	@echo Compiling ..\spec\zobraz.f90
	@$(FC) -c -o "build\zobraz.o" $(FFLAGS) "..\spec\zobraz.f90"
"modules\zobraz.mod" : "build\zobraz.o" .EXISTSONLY
	@echo Compiling ..\spec\zobraz.f90
	@$(FC) -c -o "build\zobraz.o" $(FFLAGS) "..\spec\zobraz.f90"

clean: .SYMBOLIC
	@echo Deleting build\geometry.o and related files
	@$(RM) "build\geometry.o" "modules\geometry.mod"
	@echo Deleting build\global.o and related files
	@$(RM) "build\global.o" "modules\global.mod"
	@echo Deleting build\kreslitko.o and related files
	@$(RM) "build\kreslitko.o" "modules\kreslitko.mod"
	@echo Deleting build\local.o and related files
	@$(RM) "build\local.o" "modules\local.mod"
	@echo Deleting build\main.o and related files
	@$(RM) "build\main.o"
	@echo Deleting build\mtx_jakub.o and related files
	@$(RM) "build\mtx_jakub.o" "modules\mtx_jakub.mod"
	@echo Deleting build\solvers_jakub.o and related files
	@$(RM) "build\solvers_jakub.o" "modules\solvers_jakub.mod"
	@echo Deleting build\datasetup.o and related files
	@$(RM) "build\datasetup.o" "modules\datasetup.mod"
	@echo Deleting build\fullmatrix.o and related files
	@$(RM) "build\fullmatrix.o" "modules\fullmatrix.mod"
	@echo Deleting build\mtx.o and related files
	@$(RM) "build\mtx.o" "modules\mtx.mod"
	@echo Deleting build\mtxiotools.o and related files
	@$(RM) "build\mtxiotools.o" "modules\mtxiotools.mod"
	@echo Deleting build\mtxtester.o and related files
	@$(RM) "build\mtxtester.o" "modules\mtxtester_module.mod"
	@echo Deleting build\pmatools.o and related files
	@$(RM) "build\pmatools.o" "modules\pmatools.mod"
	@echo Deleting build\pmatypy.o and related files
	@$(RM) "build\pmatypy.o" "modules\pmatypy.mod"
	@echo Deleting build\solvers.o and related files
	@$(RM) "build\solvers.o" "modules\solvers.mod"
	@echo Deleting build\sparsematrix.o and related files
	@$(RM) "build\sparsematrix.o" "modules\sparsematrix.mod"
	@echo Deleting build\zobraz.o and related files
	@$(RM) "build\zobraz.o" "modules\zobraz.mod"
	@echo Deleting Project.exe
	@$(RM) "Project.exe"

"Project.exe":  "build\geometry.o" "build\global.o" "build\kreslitko.o" "build\local.o" "build\main.o" "build\mtx_jakub.o" "build\solvers_jakub.o" "build\datasetup.o" "build\fullmatrix.o" "build\mtx.o" "build\mtxiotools.o" "build\mtxtester.o" "build\pmatools.o" "build\pmatypy.o" "build\solvers.o" "build\sparsematrix.o" "build\zobraz.o"
	@echo Generating Project.exe
	@$(FC) -o "Project.exe" -m32 "build\geometry.o" "build\global.o" "build\kreslitko.o" "build\local.o" "build\main.o" "build\mtx_jakub.o" "build\solvers_jakub.o" "build\datasetup.o" "build\fullmatrix.o" "build\mtx.o" "build\mtxiotools.o" "build\mtxtester.o" "build\pmatools.o" "build\pmatypy.o" "build\solvers.o" "build\sparsematrix.o" "build\zobraz.o" $(LDIR) $(PRJ_LFLAGS)

all: "Project.exe" .SYMBOLIC

